// Copies the pure-stdlib data layer from the Python package into the extension
// so the collector still works when slurm-monitor-top is not pip-installed in
// whatever interpreter the editor can reach. Run by `npm run compile`.
const fs = require('fs');
const path = require('path');

const MODULES = ['__init__.py', 'data.py', 'export.py'];
const src = path.resolve(__dirname, '..', '..', 'src', 'slurm_top');
const dest = path.resolve(__dirname, '..', 'python', 'slurm_top');

if (!fs.existsSync(src)) {
  // Building from a detached copy of the extension: keep whatever is bundled.
  console.log(`sync-python: ${src} not found, keeping bundled copy`);
  process.exit(0);
}

fs.mkdirSync(dest, { recursive: true });
for (const name of MODULES) {
  const from = path.join(src, name);
  if (!fs.existsSync(from)) {
    console.error(`sync-python: missing ${from}`);
    process.exit(1);
  }
  fs.copyFileSync(from, path.join(dest, name));
}
fs.writeFileSync(
  path.join(dest, '..', 'README.md'),
  'Generated by `npm run sync-python`. Do not edit here; edit `src/slurm_top/` at the repository root.\n'
);
console.log(`sync-python: copied ${MODULES.length} modules into ${dest}`);
